"""
Task A / cross-format ingestion matrix.

Because Task A concerns ingestion boundaries, this compact matrix covers
real parsing + canonicalization for the four boundary types — BED query,
GFF3/GTF annotation, custom query, custom annotation — and proves the
parser output reaches the canonical engine correctly on BOTH backends
with hand-computed expected values (never generated by the code under
test).

Fixture A (known formats):
    query  BED  chr1 [50, 100)  q1
                   chr1 [900, 950) q2
    annot  GFF3 chr1 (100, 200) strand +  -> canonical [99, 200)   a1
                   chr1 (800, 900) strand - -> canonical [799, 900) a2

    overlap (both engines):
      q1: [50,100) vs [99,200) -> 1-base overlap [99,100) -> match a1
      q2: [900,950) vs [799,900) -> touching only -> no match
           vs [99,200) -> different span -> no match
    closest (both engines):
      q1: [99,200) distance 0 (overlap); [799,900) distance 699 -> a1, 0
      q2: [799,900) distance 0 (touching); [99,200) distance 700 -> a2, 0

Fixture B (custom boundaries):
    query  custom TSV  chrom,pos,stop,name  (0-based)
                   chr1 100 200 q1
    annot  custom TSV  chr,start,end,gene   (1-based declared)
                   chr1 150 250 G1   -> canonical [149, 250)

    overlap (both engines): one match, [149, 200) intersection.
"""

from __future__ import annotations

import pytest

from streamlit_app.core import (
    CustomParser,
    normalize_intervals,
    parse_and_normalize,
)
from streamlit_app.core.annotator import BedtoolsEngine, PolarsBioEngine
from tests.parity.comparator import (
    assert_canonical_equal,
    check_expected,
    run_and_canonicalize,
)

ENGINES = [BedtoolsEngine, PolarsBioEngine]

BED_QUERY = (
    "chr1\t50\t100\tq1\n"
    "chr1\t900\t950\tq2\n"
)
GFF3_ANNOT = (
    "##gff-version 3\n"
    "chr1\tsrc\tgene\t100\t200\t.\t+\t.\tID=a1;Name=A1\n"
    "chr1\tsrc\tgene\t800\t900\t.\t-\t.\tID=a2;Name=A2\n"
)
CUSTOM_QUERY = (
    "chrom\tpos\tstop\tname\n"
    "chr1\t100\t200\tq1\n"
)
CUSTOM_ANNOT = (
    "chr\tstart\tend\tgene\n"
    "chr1\t150\t250\tG1\n"
)


@pytest.fixture(scope="module")
def known_format_tables(tmp_path_factory):
    tmp = tmp_path_factory.mktemp("known")
    (tmp / "q.bed").write_text(BED_QUERY)
    (tmp / "a.gff3").write_text(GFF3_ANNOT)
    return (
        parse_and_normalize(str(tmp / "q.bed")),
        parse_and_normalize(str(tmp / "a.gff3")),
    )


@pytest.fixture(scope="module")
def custom_tables(tmp_path_factory):
    tmp = tmp_path_factory.mktemp("custom")
    q = tmp / "q.tsv"
    q.write_text(CUSTOM_QUERY)
    a = tmp / "a.tsv"
    a.write_text(CUSTOM_ANNOT)

    q_raw = CustomParser.parse(str(q))
    q_mapped = CustomParser.map_columns(q_raw, "chrom", "pos", "stop", ["name"])
    q_df = normalize_intervals(q_mapped, coordinate_system="0-based")

    a_raw = CustomParser.parse(str(a))
    a_df = normalize_intervals(a_raw, coordinate_system="1-based")
    return q_df, a_df


class TestKnownFormatIngestion:
    @pytest.mark.parametrize("engine_cls", ENGINES)
    def test_bed_query_against_gff3_annotation_overlap(
        self, engine_cls, known_format_tables
    ):
        coord_df, annot_df = known_format_tables
        # Hand-computed: only q1 overlaps (one base [99, 100)); q2 merely
        # touches [799, 900).
        check_expected(
            engine_cls, coord_df, annot_df,
            pairs=[(0, 0)], how="inner",
        )

    @pytest.mark.parametrize("engine_cls", ENGINES)
    def test_bed_query_against_gff3_annotation_closest(
        self, engine_cls, known_format_tables
    ):
        coord_df, annot_df = known_format_tables
        # Hand-computed distances: q1 -> [99,200) overlap (0);
        # q2 -> [799,900) touching (0).
        check_expected(
            engine_cls, coord_df, annot_df,
            pairs=[(0, 0), (1, 1)], how="inner",
            distances=(0, 0), mode="closest",
        )

    def test_both_backends_agree_on_known_format_ingestion(self, known_format_tables):
        coord_df, annot_df = known_format_tables
        for mode, extra in (("overlap", ()), ("closest", ("distance",))):
            bedtools = run_and_canonicalize(
                BedtoolsEngine, coord_df, annot_df, how="inner",
                extra_columns=extra, mode=mode,
            )
            polars = run_and_canonicalize(
                PolarsBioEngine, coord_df, annot_df, how="inner",
                extra_columns=extra, mode=mode,
            )
            assert_canonical_equal(bedtools, polars, label=f"known-format {mode} parity")


class TestCustomBoundaryIngestion:
    @pytest.mark.parametrize("engine_cls", ENGINES)
    def test_custom_query_against_custom_annotation_overlap(
        self, engine_cls, custom_tables
    ):
        coord_df, annot_df = custom_tables
        # 1-based declared annotation (150, 250) -> canonical [149, 250):
        # intersects query [100, 200) at [149, 200).
        check_expected(
            engine_cls, coord_df, annot_df,
            pairs=[(0, 0)], how="inner",
        )
        # Both custom boundary tables kept their metadata columns through
        # canonicalization.
        raw = engine_cls().intersect(coord_df, annot_df, how="inner")
        from streamlit_app.core import canonicalize_annotation_result

        result = canonicalize_annotation_result(raw, coord_df, annot_df)
        assert result["coord_name"].tolist() == ["q1"]
        assert result["annot_gene"].tolist() == ["G1"]

    def test_both_backends_agree_on_custom_boundary_ingestion(self, custom_tables):
        coord_df, annot_df = custom_tables
        bedtools = run_and_canonicalize(
            BedtoolsEngine, coord_df, annot_df, how="inner"
        )
        polars = run_and_canonicalize(
            PolarsBioEngine, coord_df, annot_df, how="inner"
        )
        assert_canonical_equal(
            bedtools, polars, label="custom-boundary overlap parity"
        )

    def test_one_based_declaration_changes_the_custom_annotation(self, tmp_path):
        """Same custom annotation, two declarations -> the hand-computed
        different canonical intervals (exactly one conversion applied)."""
        a = tmp_path / "a.tsv"
        a.write_text(CUSTOM_ANNOT)
        one_based = normalize_intervals(
            CustomParser.parse(str(a)), coordinate_system="1-based"
        )
        zero_based = normalize_intervals(
            CustomParser.parse(str(a)), coordinate_system="0-based"
        )
        assert one_based[["chr", "start", "end"]].values.tolist() == [
            ["chr1", 149, 250]
        ]
        assert zero_based[["chr", "start", "end"]].values.tolist() == [
            ["chr1", 150, 250]
        ]