"""
Task C / F8 — annotated VCF export fidelity.

The exported annotated VCF must:
- preserve the original record-level content the parse/result path
  actually retained (ID, REF, ALT, QUAL, FILTER, the raw INFO field
  including END, FORMAT and sample columns);
- append annotation-derived INFO keys under the ANNOT_* namespace
  (never bare annotation column names) and declare every emitted key
  with a valid ##INFO line;
- keep POS semantics correct (POS = coord_start + 1), keep row
  multiplicity (one record per query-annotation pair), and export
  unmatched retained rows as valid records without bogus values.

Expected VCF content in these tests is hand-computed from the fixtures
below — never generated by running the exporter under test.
"""

import re

import pandas as pd
import pytest

from streamlit_app.config import Settings
from streamlit_app.core.engine_registry import build_engine
from streamlit_app.core.normalization import normalize_intervals
from streamlit_app.core.parsers import GFFParser, VCFParser
from streamlit_app.core.schema import canonicalize_annotation_result
from streamlit_app.streamlit_app import convert_df_to_vcf


# ---------------------------------------------------------------------------
# Fixtures (tiny, human-readable, hand-auditable)
# ---------------------------------------------------------------------------

QUERY_VCF = (
    b"##fileformat=VCFv4.2\n"
    b"##INFO=<ID=DP,Number=.,Type=Integer,Description=\"read depth\">\n"
    b"##INFO=<ID=END,Number=1,Type=Integer,Description=\"end position\">\n"
    b"##INFO=<ID=SVTYPE,Number=1,Type=String,Description=\"structural variant type\">\n"
    b"##FORMAT=<ID=GT,Number=1,Type=String,Description=\"genotype\">\n"
    b"##FORMAT=<ID=DP,Number=1,Type=Integer,Description=\"depth\">\n"
    b"#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1\n"
    # A/B: SNV with ID, QUAL, FILTER, INFO (DP=10), FORMAT/samples.
    b"chr1\t100\tsnv1\tA\tT\t50\tPASS\tDP=10\tGT:DP\t0/1:8\n"
    # D: symbolic variant carrying END; QUAL/FILTER missing.
    b"chr1\t300\t.\tC\t<DEL>\t.\t.\tEND=400;SVTYPE=DEL\tGT:DP\t./.:.\n"
    # F: variant with no annotation match (left join retains it).
    b"chr1\t500\tnomatch\tG\tA\t.\t.\t.\tGT:DP\t1/1:3\n"
)

ANNOT_GFF = (
    b"##gff-version 3\n"
    # E: geneA and geneB both overlap the SNV at POS 100.
    b"chr1\tens\tgene\t1\t120\t.\t+\t.\tID=geneA;Name=geneA\n"
    b"chr1\tens\tgene\t90\t110\t.\t-\t.\tID=geneB;Name=geneB\n"
    # geneC overlaps nothing in the query.
    b"chr1\tens\tgene\t900\t950\t.\t+\t.\tID=geneC;Name=geneC\n"
)

# The GFF parser publishes, in this order, the metadata columns:
# strand, source, feature, score, frame, attributes, ID, Name, gene_id,
# gene_name, transcript_id, gene_type, gene_biotype, Parent. With the
# fixture above, score/frame are "." (skipped in INFO) and the
# gene_* / Parent attributes are missing (skipped). So a matched SNV
# row gains exactly: ANNOT_strand, ANNOT_source, ANNOT_feature,
# ANNOT_attributes, ANNOT_ID, ANNOT_Name — in that order.
_GENE_A_ANNOT_INFO = (
    "ANNOT_strand=+;ANNOT_source=ens;ANNOT_feature=gene;"
    "ANNOT_attributes=ID:geneA|Name:geneA;ANNOT_ID=geneA;ANNOT_Name=geneA"
)
_GENE_B_ANNOT_INFO = (
    "ANNOT_strand=-;ANNOT_source=ens;ANNOT_feature=gene;"
    "ANNOT_attributes=ID:geneB|Name:geneB;ANNOT_ID=geneB;ANNOT_Name=geneB"
)

EXPECTED_RECORDS = [
    # E: one source variant, two annotation hits -> two records,
    # original fields identical in both, annotation payload differs.
    ["chr1", "100", "snv1", "A", "T", "50", "PASS",
     f"DP=10;{_GENE_A_ANNOT_INFO}", "GT:DP", "0/1:8"],
    ["chr1", "100", "snv1", "A", "T", "50", "PASS",
     f"DP=10;{_GENE_B_ANNOT_INFO}", "GT:DP", "0/1:8"],
    # D: unmatched; original INFO (END=400) must survive verbatim.
    ["chr1", "300", ".", "C", "<DEL>", ".", ".",
     "END=400;SVTYPE=DEL", "GT:DP", "./.:."],
    # F: unmatched; empty original INFO -> bare "." (no bogus values).
    ["chr1", "500", "nomatch", "G", "A", ".", ".",
     ".", "GT:DP", "1/1:3"],
]

EXPECTED_HEADER_NAMES = [
    "ANNOT_strand", "ANNOT_source", "ANNOT_feature", "ANNOT_score",
    "ANNOT_frame", "ANNOT_attributes", "ANNOT_ID", "ANNOT_Name",
    "ANNOT_gene_id", "ANNOT_gene_name", "ANNOT_transcript_id",
    "ANNOT_gene_type", "ANNOT_gene_biotype", "ANNOT_Parent",
]


def _export_text(tmp_path, engine: str = "bedtools") -> str:
    """Full real path: parse -> normalize -> engine -> canonicalize -> export."""
    vcf_path = tmp_path / "query.vcf"
    gff_path = tmp_path / "annot.gff"
    vcf_path.write_bytes(QUERY_VCF)
    gff_path.write_bytes(ANNOT_GFF)

    coord_df = normalize_intervals(
        VCFParser.parse(str(vcf_path)), coordinate_system="1-based"
    )
    annot_df = normalize_intervals(
        GFFParser.parse(str(gff_path)), coordinate_system="1-based"
    )
    engine_obj = build_engine(engine, mode="overlap")
    raw = engine_obj.intersect(coord_df, annot_df, how="left")
    result = canonicalize_annotation_result(raw, coord_df, annot_df)
    return convert_df_to_vcf(result)


def _data_records(vcf_text: str):
    return [
        line.split("\t")
        for line in vcf_text.splitlines()
        if line and not line.startswith("#")
    ]


def _header_lines(vcf_text: str):
    return [line for line in vcf_text.splitlines() if line.startswith("##")]


# ---------------------------------------------------------------------------
# Real-path (integration) fidelity
# ---------------------------------------------------------------------------

class TestVCFExportRealPath:
    def test_full_export_matches_hand_computed_records(self, tmp_path):
        vcf = _export_text(tmp_path)
        assert _data_records(vcf) == EXPECTED_RECORDS

    def test_header_line_includes_format_and_samples(self, tmp_path):
        vcf = _export_text(tmp_path)
        chrom_line = next(
            l for l in vcf.splitlines() if l.startswith("#CHROM")
        )
        assert chrom_line == (
            "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1"
        )

    def test_every_emitted_annot_key_is_declared(self, tmp_path):
        vcf = _export_text(tmp_path)
        declared = set(re.findall(
            r"##INFO=<ID=([A-Za-z0-9_]+),", vcf
        ))
        emitted = set()
        for record in _data_records(vcf):
            info = record[7]
            if info != ".":
                for token in info.split(";"):
                    key = token.split("=")[0]
                    if key.startswith("ANNOT_"):
                        emitted.add(key)
        assert emitted
        assert emitted <= declared, (
            f"emitted but undeclared: {sorted(emitted - declared)}"
        )

    def test_all_annot_columns_are_declared_in_header(self, tmp_path):
        vcf = _export_text(tmp_path)
        for name in EXPECTED_HEADER_NAMES:
            assert re.search(
                rf"##INFO=<ID={re.escape(name)},Number=\.,"
                rf"Type=String,Description=", vcf
            ), f"missing ##INFO declaration for {name}"

    def test_original_info_keys_are_not_fabricated_in_header(self, tmp_path):
        # The parser does not retain the original ##INFO/##FORMAT
        # definition lines, so the exporter must not invent them.
        vcf = _export_text(tmp_path)
        assert "##INFO=<ID=DP," not in vcf
        assert "##INFO=<ID=END," not in vcf
        assert "##FORMAT=" not in vcf

    def test_source_line_identifies_annotater_with_version(self, tmp_path):
        vcf = _export_text(tmp_path)
        assert f"##source=AnnotateR {Settings.VERSION}" in vcf.splitlines()
        assert "##source=AnnotatorApp" not in vcf

    def test_original_header_metadata_is_not_invented(self, tmp_path):
        # Only generated lines: fileformat/source/date/INFO declarations.
        for line in _header_lines(_export_text(tmp_path)):
            assert line.startswith(
                ("##fileformat=", "##source=AnnotateR ", "##date=",
                 '##INFO=<ID=ANNOT_')
            ), f"unexpected header line: {line}"

    def test_round_trip_reparse_accepts_export_and_keeps_content(self, tmp_path):
        vcf = _export_text(tmp_path)
        out = tmp_path / "exported.vcf"
        out.write_text(vcf)
        reparsed = VCFParser.parse(str(out))
        norm = normalize_intervals(reparsed, coordinate_system="1-based")

        assert len(norm) == 4  # multiplicity preserved across round trip
        snv = norm.loc[norm["id"] == "snv1"]
        assert len(snv) == 2  # both annotation hits survive the round trip
        for _, row in snv.iterrows():
            assert row["qual"] == 50.0
            assert row["filter"] == "PASS"
            assert row["info"].startswith("DP=10;ANNOT_strand=")
            assert "ANNOT_feature=gene" in row["info"]
        # END=400 in the preserved INFO drives the same span as before.
        dele = norm.loc[norm["alt"] == "<DEL>"].iloc[0]
        assert (dele["start"], dele["end"]) == (299, 400)
        assert "END=400;SVTYPE=DEL" == dele["info"]


# ---------------------------------------------------------------------------
# Exporter unit-level contract (hand-built result frames)
# ---------------------------------------------------------------------------

def _result_df(**overrides):
    base = {
        "coord_chr": ["chr1"],
        "coord_start": [100],
        "coord_end": [101],
        "coord_id": [pd.NA],
        "coord_ref": ["A"],
        "coord_alt": ["G"],
        "coord_qual": [pd.NA],
        "coord_filter": [pd.NA],
        "annot_feature": ["geneA"],
        "has_overlap": [True],
    }
    base.update(overrides)
    return pd.DataFrame(base)


class TestOriginalInfoPreservation:
    def test_info_appended_not_replaced(self):
        vcf = convert_df_to_vcf(
            _result_df(coord_info=["DP=10"])
        )
        record = vcf.splitlines()[-1].split("\t")
        assert record[7] == "DP=10;ANNOT_feature=geneA"

    def test_end_survives_inside_original_info(self):
        vcf = convert_df_to_vcf(
            _result_df(coord_info=["END=400;SVTYPE=DEL"],
                       coord_alt=["<DEL>"], coord_end=[400])
        )
        record = vcf.splitlines()[-1].split("\t")
        # POS stays the original 1-based POS; END stays in INFO verbatim.
        assert record[1] == "101"
        assert record[4] == "<DEL>"
        assert record[7] == f"END=400;SVTYPE=DEL;ANNOT_feature=geneA"

    def test_flag_only_info_survives(self):
        vcf = convert_df_to_vcf(_result_df(coord_info=["DB"]))
        record = vcf.splitlines()[-1].split("\t")
        assert record[7] == "DB;ANNOT_feature=geneA"

    def test_missing_info_with_annotations(self):
        vcf = convert_df_to_vcf(_result_df())  # no coord_info column
        record = vcf.splitlines()[-1].split("\t")
        assert record[7] == "ANNOT_feature=geneA"

    def test_original_info_only_no_annotations(self):
        vcf = convert_df_to_vcf(
            _result_df(coord_info=["DP=10;END=400"],
                       annot_feature=[pd.NA])
        )
        record = vcf.splitlines()[-1].split("\t")
        assert record[7] == "DP=10;END=400"


class TestAnnotationNamespace:
    def test_keys_namespaced_and_declared(self):
        vcf = convert_df_to_vcf(_result_df())
        header = _header_lines(vcf)
        record = vcf.splitlines()[-1].split("\t")
        assert record[7] == "ANNOT_feature=geneA"
        assert any(
            l == (
                "##INFO=<ID=ANNOT_feature,Number=.,Type=String,"
                'Description="AnnotateR annotation (source column: '
                'annot_feature)">'
            )
            for l in header
        )
        # No bare annotation column name may be emitted as an INFO key.
        assert not re.search(r"(^|;)feature=", record[7])

    def test_multiple_columns_all_declared_in_order(self):
        df = _result_df(annot_feature=["geneA"], annot_ID=["g1"],
                        annot_strand=["+"])
        vcf = convert_df_to_vcf(df)
        record = vcf.splitlines()[-1].split("\t")
        assert record[7] == (
            "ANNOT_feature=geneA;ANNOT_ID=g1;ANNOT_strand=+"
        )
        for key in ("ANNOT_feature", "ANNOT_ID", "ANNOT_strand"):
            assert f"##INFO=<ID={key}," in vcf


class TestQualityFilterIdFidelity:
    def test_integer_qual_not_rewritten(self):
        vcf = convert_df_to_vcf(_result_df(coord_qual=[50.0]))
        record = vcf.splitlines()[-1].split("\t")
        assert record[5] == "50"

    def test_fractional_qual_kept(self):
        vcf = convert_df_to_vcf(_result_df(coord_qual=[12.5]))
        record = vcf.splitlines()[-1].split("\t")
        assert record[5] == "12.5"

    def test_missing_qual_is_dot(self):
        vcf = convert_df_to_vcf(_result_df())
        record = vcf.splitlines()[-1].split("\t")
        assert record[5] == "."

    def test_id_ref_alt_filter_verbatim(self):
        vcf = convert_df_to_vcf(
            _result_df(coord_id=["v1"], coord_ref=["A"],
                       coord_alt=["<INS>"], coord_filter=["LowQual;PASS2"])
        )
        record = vcf.splitlines()[-1].split("\t")
        assert record[2:7] == ["v1", "A", "<INS>", ".", "LowQual;PASS2"]


class TestFormatAndSamples:
    def test_format_and_sample_columns_preserved_in_order(self):
        df = _result_df(coord_format=["GT:AD"], coord_S1=["0/1:8,2"],
                        coord_S2=["./.:."])
        vcf = convert_df_to_vcf(df)
        chrom = next(l for l in vcf.splitlines() if l.startswith("#CHROM"))
        assert chrom.endswith("\tFORMAT\tS1\tS2")
        record = vcf.splitlines()[-1].split("\t")
        assert record[8:] == ["GT:AD", "0/1:8,2", "./.:."]

    def test_sample_name_collision_prefix_is_reversed(self):
        # A sample named "start" is stored as sample_start by the
        # parser (collision rename) -> coord_sample_start in the
        # result; the export header must show the original name.
        df = _result_df(coord_format=["GT"], coord_sample_start=["0/0"])
        vcf = convert_df_to_vcf(df)
        chrom = next(l for l in vcf.splitlines() if l.startswith("#CHROM"))
        assert chrom.endswith("\tFORMAT\tstart")

    def test_no_format_column_keeps_eight_columns(self):
        vcf = convert_df_to_vcf(_result_df())
        chrom = next(l for l in vcf.splitlines() if l.startswith("#CHROM"))
        assert chrom == "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO"


class TestEscaping:
    def test_problematic_characters_are_escaped_consistently(self):
        df = _result_df(
            annot_feature=["a b"],
            annot_source=["x;y"],
            annot_ID=["k=v"],
            annot_gene_name=["a,b"],
        )
        vcf = convert_df_to_vcf(df)
        record = vcf.splitlines()[-1].split("\t")
        info = record[7]
        # Repository-established encoding: space -> '_', ';' -> '|',
        # '=' -> ':'; commas are valid in String values and pass through.
        assert info == (
            "ANNOT_feature=a_b;ANNOT_source=x|y;ANNOT_ID=k:v;"
            "ANNOT_gene_name=a,b"
        )
        # The INFO field must stay a single tab-separated column.
        assert len(record) == 8


class TestCollisions:
    def test_original_info_already_containing_annot_key_wins(self):
        # The source INFO already declares ANNOT_feature: the exporter
        # must not overwrite or duplicate it.
        df = _result_df(coord_info=["DP=10;ANNOT_feature=orig"])
        vcf = convert_df_to_vcf(df)
        record = vcf.splitlines()[-1].split("\t")
        assert record[7] == "DP=10;ANNOT_feature=orig"

    def test_duplicate_keys_after_sanitization_first_wins(self):
        # '01' sanitizes to x_01, and a column literally named 'x_01'
        # also maps to ANNOT_x_01: deterministic first-in-frame-order
        # wins, no duplicate keys in the INFO field.
        df = pd.DataFrame({
            "coord_chr": ["chr1"], "coord_start": [100],
            "coord_end": [101], "has_overlap": [True],
            "annot_01": ["first"], "annot_x_01": ["second"],
        })
        vcf = convert_df_to_vcf(df)
        record = vcf.splitlines()[-1].split("\t")
        info = record[7]
        assert info.count("ANNOT_x_01=") == 1
        assert info == "ANNOT_x_01=first"


class TestUnmatchedAndMultiplicity:
    def test_unmatched_row_no_bogus_values(self):
        df = _result_df(
            coord_info=["DP=10"], annot_feature=[pd.NA],
            annot_strand=[pd.NA], has_overlap=[False],
        )
        vcf = convert_df_to_vcf(df)
        record = vcf.splitlines()[-1].split("\t")
        assert record[7] == "DP=10"
        for token in ("nan", "None", "<NA>"):
            assert token not in vcf

    def test_one_variant_two_matches_exports_two_records(self):
        df = pd.DataFrame({
            "coord_chr": ["chr1", "chr1"],
            "coord_start": [99, 99],
            "coord_end": [100, 100],
            "coord_id": ["snv1", "snv1"],
            "coord_ref": ["A", "A"],
            "coord_alt": ["T", "T"],
            "coord_qual": [50.0, 50.0],
            "coord_filter": ["PASS", "PASS"],
            "coord_info": ["DP=10", "DP=10"],
            "annot_feature": ["geneA", "geneB"],
            "has_overlap": [True, True],
        })
        vcf = convert_df_to_vcf(df)
        records = _data_records(vcf)
        assert records == [
            ["chr1", "100", "snv1", "A", "T", "50", "PASS",
             "DP=10;ANNOT_feature=geneA"],
            ["chr1", "100", "snv1", "A", "T", "50", "PASS",
             "DP=10;ANNOT_feature=geneB"],
        ]

    def test_engine_parity_of_exported_records(self, tmp_path):
        a = _export_text(tmp_path, "bedtools")
        b = _export_text(tmp_path, "polars-bio")
        assert _data_records(a) == _data_records(b)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])