"""
Task C / F8b — preservation of original VCF header (``##``) metadata.

The parse/result path retains original record values (INFO/DP, INFO/END,
FORMAT/GT, sample values, FILTER names), so the exported annotated VCF
must also carry the corresponding original ``##`` definitions —
``##contig``, ``##INFO``, ``##FORMAT``, ``##FILTER`` — otherwise the
exported file references definitions that no longer exist and is not
standards-compliant, even though AnnotateR's own parser would still
accept it.

Contract under test:
- original ``##`` lines are retained verbatim, in stable source order,
  once per source VCF (not per result row);
- exactly one ``##fileformat`` line, keeping the source's version
  (never silently upgraded/downgraded);
- original definitions are preserved, never re-synthesized;
- AnnotateR adds ``##source=AnnotateR <version>`` and ``##INFO``
  declarations for the ``ANNOT_*`` keys it emits;
- a pre-existing original declaration of an ``ANNOT_*`` ID with
  ``Type=String`` is kept as-is (no duplicate); any other type is
  refused with an explicit error (no silent overwrite);
- the export remains structurally valid and re-parses through
  AnnotateR's own VCF parser; an independent VCF library (pysam, when
  already installed) is used as an additional check where available.

Expected VCF content is hand-computed from the fixtures below — never
generated by running the exporter under test.
"""

import re
import tempfile
from pathlib import Path

import pandas as pd
import pytest

from streamlit_app.config import Settings
from streamlit_app.core.engine_registry import build_engine
from streamlit_app.core.normalization import parse_and_normalize
from streamlit_app.core.parsers import GFFParser, VCFParser
from streamlit_app.core.schema import canonicalize_annotation_result
from streamlit_app.streamlit_app import convert_df_to_vcf

QUERY_VCF = (
    b"##fileformat=VCFv4.2\n"
    b"##contig=<ID=chr1,length=1000>\n"
    b'##FILTER=<ID=LowQual,Description="low quality">\n'
    b'##INFO=<ID=DP,Number=.,Type=Integer,Description="read depth">\n'
    b'##INFO=<ID=END,Number=1,Type=Integer,Description="end position">\n'
    b'##INFO=<ID=SVTYPE,Number=1,Type=String,Description="structural variant type">\n'
    b'##FORMAT=<ID=GT,Number=1,Type=String,Description="genotype">\n'
    b"#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1\n"
    b"chr1\t100\tsnv1\tA\tT\t50\tPASS\tDP=10\tGT\t0/1\n"
    b"chr1\t300\t.\tC\t<DEL>\t.\tLowQual\tEND=400;SVTYPE=DEL\tGT\t./.\n"
)

ORIGINAL_HEADER_LINES = [
    "##fileformat=VCFv4.2",
    "##contig=<ID=chr1,length=1000>",
    '##FILTER=<ID=LowQual,Description="low quality">',
    '##INFO=<ID=DP,Number=.,Type=Integer,Description="read depth">',
    '##INFO=<ID=END,Number=1,Type=Integer,Description="end position">',
    '##INFO=<ID=SVTYPE,Number=1,Type=String,Description="structural variant type">',
    '##FORMAT=<ID=GT,Number=1,Type=String,Description="genotype">',
]

ANNOT_GFF = (
    b"##gff-version 3\n"
    b"chr1\tens\tgene\t1\t120\t.\t+\t.\tID=geneA;Name=geneA\n"
    b"chr1\tens\tgene\t90\t110\t.\t-\t.\tID=geneB;Name=geneB\n"
    b"chr1\tens\tgene\t900\t950\t.\t+\t.\tID=geneC;Name=geneC\n"
)

ANNOT_DECLARATIONS = [
    (key, col)
    for key, col in [
        ("ANNOT_strand", "annot_strand"),
        ("ANNOT_source", "annot_source"),
        ("ANNOT_feature", "annot_feature"),
        ("ANNOT_score", "annot_score"),
        ("ANNOT_frame", "annot_frame"),
        ("ANNOT_attributes", "annot_attributes"),
        ("ANNOT_ID", "annot_ID"),
        ("ANNOT_Name", "annot_Name"),
        ("ANNOT_gene_id", "annot_gene_id"),
        ("ANNOT_gene_name", "annot_gene_name"),
        ("ANNOT_transcript_id", "annot_transcript_id"),
        ("ANNOT_gene_type", "annot_gene_type"),
        ("ANNOT_gene_biotype", "annot_gene_biotype"),
        ("ANNOT_Parent", "annot_Parent"),
    ]
]


def _declaration(key: str, col: str) -> str:
    return (
        f'##INFO=<ID={key},Number=.,Type=String,'
        f'Description="AnnotateR annotation (source column: {col})">'
    )


def _write(directory: Path, name: str, data: bytes) -> str:
    path = directory / name
    path.write_bytes(data)
    return str(path)


def _full_export(query_vcf: bytes, annot_gff: bytes = ANNOT_GFF,
                 engine_name: str = "bedtools") -> str:
    """
    Real path mirroring the app's plumbing: parse (headers retained on
    the frame) -> normalize -> engine -> canonicalize -> export with the
    retained header lines, exactly as the app passes them from session
    state to the exporter.
    """
    d = Path(tempfile.mkdtemp())
    q = parse_and_normalize(_write(d, "q.vcf", query_vcf))
    a = parse_and_normalize(_write(d, "a.gff", annot_gff))
    raw = build_engine(engine_name, mode="overlap").intersect(q, a, how="left")
    result = canonicalize_annotation_result(raw, q, a)
    return convert_df_to_vcf(result, original_header_lines=q.attrs.get(
        "vcf_header_lines"))


def _header_lines(vcf_text: str):
    return [l for l in vcf_text.splitlines() if l.startswith("##")]


def _record_lines(vcf_text: str):
    return [l for l in vcf_text.splitlines()
            if l and not l.startswith("#")]


EXPECTED_RECORDS = [
    "chr1\t100\tsnv1\tA\tT\t50\tPASS\tDP=10;ANNOT_strand=+;ANNOT_source=ens;"
    "ANNOT_feature=gene;ANNOT_attributes=ID:geneA|Name:geneA;"
    "ANNOT_ID=geneA;ANNOT_Name=geneA\tGT\t0/1",
    "chr1\t100\tsnv1\tA\tT\t50\tPASS\tDP=10;ANNOT_strand=-;ANNOT_source=ens;"
    "ANNOT_feature=gene;ANNOT_attributes=ID:geneB|Name:geneB;"
    "ANNOT_ID=geneB;ANNOT_Name=geneB\tGT\t0/1",
    "chr1\t300\t.\tC\t<DEL>\t.\tLowQual\tEND=400;SVTYPE=DEL\tGT\t./.",
]


# ---------------------------------------------------------------------------
# Parser / normalization: header metadata retention
# ---------------------------------------------------------------------------

class TestHeaderRetentionPlumbing:
    def test_parser_attaches_header_lines_in_source_order(self):
        d = Path(tempfile.mkdtemp())
        df = VCFParser.parse(_write(d, "q.vcf", QUERY_VCF))
        assert df.attrs["vcf_header_lines"] == ORIGINAL_HEADER_LINES
        # Retention must not add columns: the schema is unchanged.
        assert "vcf_header_lines" not in df.columns

    def test_vcf_without_header_lines_gets_empty_list(self):
        d = Path(tempfile.mkdtemp())
        minimal = (
            b"#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n"
            b"chr1\t5\t.\tA\tT\t.\t.\t.\n"
        )
        df = VCFParser.parse(_write(d, "q.vcf", minimal))
        assert df.attrs["vcf_header_lines"] == []

    def test_parse_and_normalize_propagates_header_lines(self):
        d = Path(tempfile.mkdtemp())
        q = parse_and_normalize(_write(d, "q.vcf", QUERY_VCF))
        assert q.attrs["vcf_header_lines"] == ORIGINAL_HEADER_LINES


# ---------------------------------------------------------------------------
# Export: original metadata survives, generated content coexists
# ---------------------------------------------------------------------------

class TestHeaderSurvivesExport:
    def test_original_info_dp_declaration_survives(self):
        out = _full_export(QUERY_VCF)
        assert (
            '##INFO=<ID=DP,Number=.,Type=Integer,Description="read depth">'
            in _header_lines(out)
        )

    def test_original_info_end_declaration_and_value_survive(self):
        out = _full_export(QUERY_VCF)
        header = _header_lines(out)
        assert (
            '##INFO=<ID=END,Number=1,Type=Integer,Description="end position">'
            in header
        )
        # And the corresponding record value is still there.
        assert "END=400" in _record_lines(out)[2]

    def test_original_format_gt_declaration_survives(self):
        out = _full_export(QUERY_VCF)
        assert (
            '##FORMAT=<ID=GT,Number=1,Type=String,Description="genotype">'
            in _header_lines(out)
        )

    def test_original_contig_declaration_survives(self):
        out = _full_export(QUERY_VCF)
        assert "##contig=<ID=chr1,length=1000>" in _header_lines(out)

    def test_original_filter_declaration_survives(self):
        out = _full_export(QUERY_VCF)
        assert (
            '##FILTER=<ID=LowQual,Description="low quality">'
            in _header_lines(out)
        )

    def test_annot_declarations_coexist_with_originals(self):
        out = _full_export(QUERY_VCF)
        header = _header_lines(out)
        # Originals and generated declarations side by side.
        assert '##INFO=<ID=DP,' in "\n".join(header)
        assert all(_declaration(k, c) in header for k, c in ANNOT_DECLARATIONS)
        # Every ANNOT_* key actually used in a record is declared.
        header_text = "\n".join(header)
        for record in _record_lines(out):
            info = record.split("\t")[7]
            for token in info.split(";"):
                key = token.split("=", 1)[0]
                if key.startswith("ANNOT_"):
                    assert re.search(
                        rf"^##INFO=<ID={re.escape(key)}[>,]", header_text,
                        flags=re.M,
                    ), f"emitted INFO key {key} has no ##INFO declaration"

    def test_header_metadata_emitted_once_despite_multiple_rows(self):
        # snv1 matches two genes -> three records total, but the header
        # belongs to the source VCF, not to a result row.
        out = _full_export(QUERY_VCF)
        assert len(_record_lines(out)) == 3
        assert out.count("##fileformat") == 1
        assert out.count("##contig") == 1
        assert out.count("##source=AnnotateR") == 1
        assert out.count('##INFO=<ID=DP,') == 1
        assert out.count('##FORMAT=<ID=GT,') == 1
        assert out.count('##FILTER=<ID=LowQual,') == 1

    def test_single_fileformat_preserves_source_version(self):
        out = _full_export(QUERY_VCF)
        fileformat_lines = [l for l in _header_lines(out)
                            if l.startswith("##fileformat")]
        assert fileformat_lines == ["##fileformat=VCFv4.2"]

    def test_fileformat_version_not_upgraded_or_downgraded(self):
        v41 = QUERY_VCF.replace(b"##fileformat=VCFv4.2\n",
                                b"##fileformat=VCFv4.1\n")
        out = _full_export(v41)
        fileformat_lines = [l for l in _header_lines(out)
                            if l.startswith("##fileformat")]
        assert fileformat_lines == ["##fileformat=VCFv4.1"]
        assert "##fileformat=VCFv4.2" not in out

    def test_original_metadata_order_stable_and_deterministic(self):
        out1 = _full_export(QUERY_VCF)
        out2 = _full_export(QUERY_VCF)
        header1 = _header_lines(out1)
        # Relative order of the retained originals equals source order
        # (fileformat is normalized to position 0 by contract).
        non_fileformat = [line for line in ORIGINAL_HEADER_LINES
                          if not line.startswith("##fileformat")]
        positions = [header1.index(line) for line in non_fileformat]
        assert positions == sorted(positions)
        # Generated ANNOT_* declarations come after the original block.
        last_original = max(positions)
        first_annot = min(header1.index(l) for l in header1
                          if l.startswith("##INFO=<ID=ANNOT_"))
        assert first_annot > last_original
        # Deterministic across runs.
        assert _header_lines(out1) == _header_lines(out2)

    def test_duplicate_identical_original_declaration_emitted_once(self):
        duped = QUERY_VCF.replace(
            b'##INFO=<ID=DP,Number=.,Type=Integer,Description="read depth">\n',
            b'##INFO=<ID=DP,Number=.,Type=Integer,Description="read depth">\n'
            b'##INFO=<ID=DP,Number=.,Type=Integer,Description="read depth">\n',
        )
        out = _full_export(duped)
        assert out.count(
            '##INFO=<ID=DP,Number=.,Type=Integer,Description="read depth">'
        ) == 1

    def test_multiple_fileformat_lines_collapse_to_first(self):
        qv = b"""##fileformat=VCFv4.1
##fileformat=VCFv4.2
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO
chr1\t100\t.\tA\tT\t50\tPASS\t.
"""
        out = _full_export(qv)
        fileformats = [
            line for line in _header_lines(out)
            if line.lower().startswith("##fileformat")
        ]
        assert fileformats == ["##fileformat=VCFv4.1"]

    def test_original_source_preserved_and_annotater_source_added(self):
        with_source = QUERY_VCF.replace(
            b"##contig=<ID=chr1,length=1000>\n",
            b"##contig=<ID=chr1,length=1000>\n##source=OriginalPipeline v1.3\n",
        )
        out = _full_export(with_source)
        header = _header_lines(out)
        assert "##source=OriginalPipeline v1.3" in header
        assert f"##source=AnnotateR {Settings.VERSION}" in header
        # The original line is kept, never replaced: original order first.
        assert header.index("##source=OriginalPipeline v1.3") < \
            header.index(f"##source=AnnotateR {Settings.VERSION}")

    def test_format_and_samples_aligned_with_declarations(self):
        out = _full_export(QUERY_VCF)
        lines = out.splitlines()
        chrom = next(l for l in lines if l.startswith("#CHROM"))
        assert chrom.split("\t") == [
            "#CHROM", "POS", "ID", "REF", "ALT", "QUAL", "FILTER",
            "INFO", "FORMAT", "S1",
        ]
        for record in _record_lines(out):
            fields = record.split("\t")
            assert len(fields) == 10
            assert fields[8] in ("GT", ".")  # FORMAT aligns with the GT
            # declaration; sample value under the S1 header column.
        assert _record_lines(out)[0].split("\t")[9] == "0/1"
        assert _record_lines(out)[2].split("\t")[9] == "./."

    def test_exported_file_matches_hand_computed_expectation(self):
        out = _full_export(QUERY_VCF)
        today = pd.Timestamp.now().strftime("%Y%m%d")
        expected_header = [
            "##fileformat=VCFv4.2",
            "##contig=<ID=chr1,length=1000>",
            '##FILTER=<ID=LowQual,Description="low quality">',
            '##INFO=<ID=DP,Number=.,Type=Integer,Description="read depth">',
            '##INFO=<ID=END,Number=1,Type=Integer,Description="end position">',
            '##INFO=<ID=SVTYPE,Number=1,Type=String,'
            'Description="structural variant type">',
            '##FORMAT=<ID=GT,Number=1,Type=String,Description="genotype">',
            f"##source=AnnotateR {Settings.VERSION}",
            f"##date={today}",
        ] + [_declaration(k, c) for k, c in ANNOT_DECLARATIONS]
        expected = "\n".join(
            expected_header
            + ["#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS1"]
            + EXPECTED_RECORDS
        )
        assert out == expected


# ---------------------------------------------------------------------------
# ANNOT_* ID collision policy
# ---------------------------------------------------------------------------

class TestAnnotIdCollisions:
    def test_string_typed_original_annot_declaration_is_kept(self):
        pre = (
            b"##fileformat=VCFv4.2\n"
            b'##INFO=<ID=ANNOT_feature,Number=1,Type=String,'
            b'Description="pre-existing feature">\n'
            b"#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n"
            b"chr1\t100\tsnv1\tA\tT\t50\tPASS\t.\n"
        )
        out = _full_export(pre)
        header = _header_lines(out)
        original = (
            '##INFO=<ID=ANNOT_feature,Number=1,Type=String,'
            'Description="pre-existing feature">'
        )
        # The original definition stands; no generated duplicate.
        assert header.count(original) == 1
        assert _declaration("ANNOT_feature", "annot_feature") not in header
        # The value is still exported under the original definition.
        assert any(
            "ANNOT_feature=gene" in r.split("\t")[7]
            for r in _record_lines(out)
        )

    def test_incompatible_original_annot_declaration_fails_clearly(self):
        pre = (
            b"##fileformat=VCFv4.2\n"
            b'##INFO=<ID=ANNOT_source,Number=1,Type=Float,'
            b'Description="pre-existing numeric field">\n'
            b"#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n"
            b"chr1\t100\tsnv1\tA\tT\t50\tPASS\t.\n"
        )
        with pytest.raises(ValueError, match="ANNOT_source"):
            _full_export(pre)


# ---------------------------------------------------------------------------
# Structural validity + re-parse + independent validation
# ---------------------------------------------------------------------------

class TestStructuralValidity:
    def test_every_used_info_id_has_a_declaration(self):
        out = _full_export(QUERY_VCF)
        header_text = "\n".join(_header_lines(out))
        for record in _record_lines(out):
            for token in record.split("\t")[7].split(";"):
                key = token.split("=", 1)[0]
                assert re.search(
                    rf"^##INFO=<ID={re.escape(key)}[>,]", header_text,
                    flags=re.M,
                ), f"INFO key {key!r} used in a record but not declared"

    def test_every_used_format_id_is_declared(self):
        out = _full_export(QUERY_VCF)
        header_text = "\n".join(_header_lines(out))
        for record in _record_lines(out):
            for sub in record.split("\t")[8].split(":"):
                assert re.search(
                    rf"^##FORMAT=<ID={re.escape(sub)}[>,]", header_text,
                    flags=re.M,
                ), f"FORMAT sub-field {sub!r} used but not declared"

    def test_used_nonpass_filters_have_definitions(self):
        out = _full_export(QUERY_VCF)
        header_text = "\n".join(_header_lines(out))
        for record in _record_lines(out):
            filt = record.split("\t")[6]
            if filt not in (".", "PASS"):
                for name in filt.split(";"):
                    assert re.search(
                        rf"^##FILTER=<ID={re.escape(name)}[>,]", header_text,
                        flags=re.M,
                    ), f"filter {name!r} used but not defined"

    def test_record_width_matches_chrom_header(self):
        out = _full_export(QUERY_VCF)
        lines = out.splitlines()
        chrom = next(l for l in lines if l.startswith("#CHROM")).split("\t")
        for record in _record_lines(out):
            assert len(record.split("\t")) == len(chrom)


class TestReparseRoundTrip:
    def test_export_reparses_through_annotater_parser(self):
        out = _full_export(QUERY_VCF)
        d = Path(tempfile.mkdtemp())
        path = _write(d, "out.vcf", out.encode())
        df = VCFParser.parse(path)
        assert len(df) == 3
        snv = df[df["id"] == "snv1"]
        assert len(snv) == 2
        assert snv.iloc[0]["qual"] == 50.0
        assert str(snv.iloc[0]["info"]).startswith("DP=10;")
        assert snv.iloc[0]["filter"] == "PASS"
        assert snv.iloc[0]["format"] == "GT"
        assert snv.iloc[0]["S1"] == "0/1"
        dele = df[df["alt"] == "<DEL>"]
        assert len(dele) == 1
        # The END-derived span survives the round trip (1-based 300..400).
        assert int(dele.iloc[0]["start"]) == 300
        assert int(dele.iloc[0]["end"]) == 400
        assert dele.iloc[0]["filter"] == "LowQual"
        assert dele.iloc[0]["S1"] == "./."


class TestIndependentPysamValidation:
    """
    Independent of AnnotateR's own parser: pysam (already present in the
    development environment, NOT a new project dependency) must accept
    the export and see the retained metadata. Skipped where pysam is
    not installed; the structural assertions above remain the mandatory
    checks in that case.
    """

    def test_pysam_accepts_export_and_sees_retained_metadata(self):
        pysam = pytest.importorskip(
            "pysam", reason="independent VCF validation needs pysam"
        )
        out = _full_export(QUERY_VCF)
        d = Path(tempfile.mkdtemp())
        path = _write(d, "out.vcf", out.encode())

        def _scalar(value):
            # pysam returns Number=1/. INFO values as tuples.
            return value[0] if isinstance(value, tuple) else value

        with pysam.VariantFile(path) as vf:
            header = vf.header
            # Retained definitions are visible to an external consumer.
            assert "chr1" in header.contigs
            for info_id in ("DP", "END", "SVTYPE"):
                assert info_id in header.info, (
                    f"retained ##INFO declaration {info_id!r} not visible "
                    "to pysam"
                )
            assert "GT" in header.formats
            assert "LowQual" in header.filters
            # Generated provenance is visible too.
            assert any(
                line.startswith(f"##source=AnnotateR {Settings.VERSION}")
                for line in _header_lines(out)
            )
            records = list(vf)
            assert len(records) == 3
            snv = records[0]
            assert snv.chrom == "chr1" and snv.pos == 100
            assert _scalar(snv.info["DP"]) == 10
            assert snv.samples["S1"]["GT"] == (0, 1)
            dele = records[2]
            # pysam exposes INFO/END via record.stop (reserved attribute).
            assert dele.stop == 400
            assert _scalar(dele.info["SVTYPE"]) == "DEL"
            assert dele.samples["S1"]["GT"] == (None, None)